---
- hosts: localhost
  roles:
    - { role: "fedora", when: (ansible_distribution == 'Fedora') }
    - { role: "ubuntu", when: (ansible_distribution == 'Ubuntu') }
    - zsh
  vars:
    ansible_user_id: mrc