---
- name: Upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: yes

- name: Add rpmfusion free
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  become: yes

- name: Add rpmfusion nonfree
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  become: yes

- name: Add FiraCode fonts repo
  command: 'dnf copr enable evana/fira-code-fonts -y'
  become: yes

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: latest
  become: yes

- name: Install Google Chrome
  dnf:
    name: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
    state: latest
  become: yes

- name: Add the Flathub repository
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: yes

- name: Install Spotify Flatpak
  shell: flatpak install flathub com.spotify.Client -y
  become: yes

- name: Install Remmina Flatpak
  shell: flatpak install flathub org.remmina.Remmina -y
  become: yes

- name: Install Telegram Flatpak
  shell: flatpak install flathub org.telegram.desktop -y
  become: yes

- name: Install RocketChat Flatpak
  shell: flatpak install flathub chat.rocket.RocketChat -y
  become: yes

- name: Create symbolic link for snap
  file:
    src: "/var/lib/snapd/snap"
    dest: "/snap"
    state: link
  become: yes

- name: Install snap packages
  snap:
    name: "{{ snap_packages }}"
  become: yes

- name: Install snap packages --classic
  snap:
    name: "{{ snap_classic_packages }}"
    classic: yes
  become: yes

- name: Install VirtualBox Fedora 31
  dnf:
    name: https://download.virtualbox.org/virtualbox/6.1.2/VirtualBox-6.1-6.1.2_135662_fedora31-1.x86_64.rpm
    state: latest
  become: yes