---
- name: Download Oh-My-Zsh
  get_url:
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/zsh-installer.sh

- name: Execution permission to zsh-installer
  file: 
    dest: /tmp/zsh-installer.sh
    mode: a+x

- name: Execute the zsh-installer.sh for user
  script: /tmp/zsh-installer.sh
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Execute the zsh-installer.sh for root
  script: /tmp/zsh-installer.sh
  become: yes
  become_user: root

- name: Remove .zshrc file (delete file) for user
  file:
    path: ~/.zshrc
    state: absent
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Remove .zshrc file (delete file) for root
  file:
    path: /root/.zshrc
    state: absent
  become: yes

- name: copy .zshrc file for user
  template:
    src: "templates/zshrc.j2"
    dest: "/home/{{ ansible_user_id }}/.zshrc"
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: copy .zshrc file for root
  template:
    src: "templates/zshrc.j2"
    dest: "/root/.zshrc"
  become: yes

- name: Create a zsh plugins directory for user if it does not exist for user
  file:
    path: ~/.oh-my-zsh/custom/plugins/
    state: directory
    mode: '0755'
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Create a zsh plugins directory for root if it does not exist for root
  file:
    path: /root/.oh-my-zsh/custom/plugins/
    state: directory
    mode: '0755'
  become: yes

- name: Clone zsh-syntax-highlighting repo for user
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Clone zsh-autosuggestions repo for user
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Clone zsh-syntax-highlighting repo for root
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  become: yes

- name: Clone zsh-autosuggestions repo for root
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: yes

- name: Clone spaceship repo for user
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/spaceship-prompt"
  become: yes
  become_user: "{{ ansible_user_id }}"

- name: Clone spaceship repo for root
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: /root/.oh-my-zsh/custom/themes/spaceship-prompt
  become: yes
  become_user: root

- name: Create symbolic link for spaceship for user
  file:
    src: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "/home/{{ ansible_user_id }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
  become: yes

- name: Create symbolic link for spaceship for root
  file:
    src: "/root/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "/root/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
  become: yes

- name: Change shell padrão for user
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh

- name: Change shell padrão for root
  user:
    name: root
    shell: /usr/bin/zsh

- name: change zsh permissions for user
  file:
    path: "/home/{{ ansible_user_id }}/.oh-my-zsh/"
    state: directory
    recurse: yes
    mode: '0755'
  become: yes

- name: change zsh permissions for root
  file:
    path: /root/.oh-my-zsh/
    state: directory
    recurse: yes
    mode: '0755'
  become: yes
