---
- name: Download Oh-My-Zsh
  get_url:
    url: https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh 
    dest: /tmp/zsh-installer.sh

- name: Execution permission to zsh-installer
  file: 
    dest: /tmp/zsh-installer.sh
    mode: a+x

- name: Execute the zsh-installer.sh
  shell: /tmp/zsh-installer.sh
  become: yes

- name: Execute the zsh-installer.sh
  shell: /tmp/zsh-installer.sh
  become: yes
  become_user: mrc

- name: Remove .zshrc file (delete file)
  file:
    path: ~/.zshrc
    state: absent
  become: yes
  become_user: mrc

- name: Remove .zshrc file (delete file)
  file:
    path: /root/.zshrc
    state: absent
  become: yes

- name: copy .zshrc file
  copy:
    src: 'files/zshrc'
    dest: '~/.zshrc'
  become: yes
  become_user: mrc

- name: copy .zshrc file
  copy:
    src: 'files/zshrc'
    dest: '/root/.zshrc'
  become: yes

- name: Create a zsh plugins directory for user if it does not exist
  file:
    path: ~/.oh-my-zsh/custom/plugins/
    state: directory
    mode: '0755'
  become: yes
  become_user: mrc

- name: Create a zsh plugins directory for root if it does not exist
  file:
    path: /root/.oh-my-zsh/custom/plugins/
    state: directory
    mode: '0755'
  become: yes

- name: Clone zsh-syntax-highlighting repo for user
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /home/mrc/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  become: yes
  become_user: mrc

- name: Clone zsh-autosuggestions repo for user
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /home/mrc/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: yes
  become_user: mrc

- name: Clone zsh-syntax-highlighting repo for root
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  become: yes

- name: Clone zsh-autosuggestions repo for root
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: /root/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  become: yes

- name: Clone spaceship repo for user
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: /home/mrc/.oh-my-zsh/custom/themes/spaceship-prompt
  become: yes
  become_user: mrc

- name: Clone spaceship repo for root
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: /root/.oh-my-zsh/custom/themes/spaceship-prompt
  become: yes
  become_user: root

- name: Create symbolic link for spaceship for root
  file:
    src: "/root/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "/root/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
  become: yes

- name: Create symbolic link for spaceship for user
  file:
    src: "/home/mrc/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme"
    dest: "/home/mrc/.oh-my-zsh/custom/themes/spaceship.zsh-theme"
    state: link
  become: yes

- name: Add FiraCode fonts repo
  command: 'dnf copr enable evana/fira-code-fonts -y'
  become: yes

- name: Install FiraCode fonts
  dnf:
    name: fira-code-fonts
  become: yes

- name: Change shell padrão
  user:
    name: mrc
    shell: /usr/bin/zsh

- name: Change shell padrão
  user:
    name: root
    shell: /usr/bin/zsh

- name: change zsh permissions
  file:
    path: /home/mrc/.oh-my-zsh/
    state: directory
    recurse: yes
    mode: '0755'
  become: yes

- name: change zsh permissions
  file:
    path: /root/.oh-my-zsh/
    state: directory
    recurse: yes
    mode: '0755'
  become: yes