---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: yes

- name: Update all packages to the latest version
  apt:
    name: "*"
    state: latest
  become: yes

- name: Install packages
  apt:
    name: "{{ packages }}"
    state: latest
  become: yes

- name: Download Google Chrome
  get_url: 
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb
    mode: '0755'

- name: Install Google Chrome
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
  become: yes

- name: Add the Flathub repository
  shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: yes

- name: apt-get update
  apt:
    update_cache: yes
  become: yes

- name: Install Spotify Flatpak
  shell: flatpak install flathub com.spotify.Client -y
  become: yes

- name: Install Remmina Flatpak
  shell: flatpak install flathub org.remmina.Remmina -y
  become: yes

- name: Install Telegram Flatpak
  shell: flatpak install flathub org.telegram.desktop -y
  become: yes

- name: Install RocketChat Flatpak
  shell: flatpak install flathub chat.rocket.RocketChat -y
  become: yes

- name: Install snap packages
  snap:
    name: "{{ snap_packages }}"
  become: yes

- name: Install snap packages --classic
  snap:
    name: "{{ snap_classic_packages }}"
    classic: yes
  become: yes

- name: Download VirtualBox for Ubuntu 18.04 LTS
  get_url: 
    url: https://download.virtualbox.org/virtualbox/6.1.2/virtualbox-6.1_6.1.2-135662~Ubuntu~bionic_amd64.deb
    dest: /tmp/virtualbox-6.1_6.1.2-135662~Ubuntu~bionic_amd64.deb
    mode: '0755'

- name: Install VirtualBox for Ubuntu 18.04 LTS
  apt:
    deb: /tmp/virtualbox-6.1_6.1.2-135662~Ubuntu~bionic_amd64.deb
  become: yes